// Demo product catalog for "npm run seed". Images are from Unsplash (public, no key needed).
module.exports = [
  { name: 'Classic Crewneck Tee', description: 'A soft, heavyweight cotton crewneck that holds its shape wash after wash. Everyday essential in a relaxed fit.', price: 799, category: 'Apparel', image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?w=800&q=80', stock: 40, rating: 4.5, specifications: [{ label: 'Material', value: '100% cotton' }, { label: 'Fit', value: 'Relaxed' }] },
  { name: 'Oversized Hoodie', description: 'Brushed-fleece hoodie with a dropped shoulder and kangaroo pocket, built for cold-weather layering.', price: 1899, category: 'Apparel', image: 'https://images.unsplash.com/photo-1556821840-3a63f95609a7?w=800&q=80', stock: 25, rating: 4.7, specifications: [{ label: 'Material', value: 'Cotton-poly fleece' }, { label: 'Fit', value: 'Oversized' }] },
  { name: 'Tailored Chino Trousers', description: 'Slim-tapered chinos in stretch cotton twill, equally at home in the office or on the weekend.', price: 1699, category: 'Apparel', image: 'https://images.unsplash.com/photo-1473966968600-fa801b869a1a?w=800&q=80', stock: 30, rating: 4.3, specifications: [{ label: 'Material', value: 'Cotton twill' }, { label: 'Fit', value: 'Slim-tapered' }] },
  { name: 'Minimalist Denim Jacket', description: 'A trucker jacket in rigid non-stretch denim, made to soften and fade with wear.', price: 2499, category: 'Apparel', image: 'https://images.unsplash.com/photo-1543076447-215ad9ba6923?w=800&q=80', stock: 18, rating: 4.6, specifications: [{ label: 'Material', value: '100% cotton denim' }] },
  { name: 'Everyday Runner Sneakers', description: 'Lightweight knit sneakers with a cushioned sole built for all-day comfort.', price: 2999, category: 'Footwear', image: 'https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&q=80', stock: 35, rating: 4.8, specifications: [{ label: 'Upper', value: 'Knit mesh' }, { label: 'Sole', value: 'EVA cushioned' }] },
  { name: 'Leather Chelsea Boots', description: 'Full-grain leather Chelsea boots with an elastic side panel and a stacked heel.', price: 4499, category: 'Footwear', image: 'https://images.unsplash.com/photo-1638247025967-b4e38f787b76?w=800&q=80', stock: 15, rating: 4.4, specifications: [{ label: 'Material', value: 'Full-grain leather' }] },
  { name: 'Canvas Low-Top Sneakers', description: 'A classic canvas low-top with a rubber toe cap, built to be worn in.', price: 1799, category: 'Footwear', image: 'https://images.unsplash.com/photo-1525966222134-fcfa99b8ae77?w=800&q=80', stock: 42, rating: 4.2, specifications: [{ label: 'Material', value: 'Canvas' }] },
  { name: 'Minimal Leather Wallet', description: 'A slim bifold wallet in vegetable-tanned leather with six card slots.', price: 999, category: 'Accessories', image: 'https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&q=80', stock: 50, rating: 4.6, specifications: [{ label: 'Material', value: 'Vegetable-tanned leather' }] },
  { name: 'Stainless Steel Watch', description: 'A clean, minimal dial watch on a brushed stainless steel bracelet.', price: 5999, category: 'Accessories', image: 'https://images.unsplash.com/photo-1524805444758-089113d48a6d?w=800&q=80', stock: 12, rating: 4.7, specifications: [{ label: 'Case', value: 'Stainless steel' }, { label: 'Water resistance', value: '5 ATM' }] },
  { name: 'Polarized Sunglasses', description: 'Acetate frame sunglasses with polarized lenses for everyday glare-free wear.', price: 1499, category: 'Accessories', image: 'https://images.unsplash.com/photo-1572635196237-14b3f281503f?w=800&q=80', stock: 28, rating: 4.1, specifications: [{ label: 'Lens', value: 'Polarized' }] },
  { name: 'Canvas Tote Bag', description: 'A durable canvas tote with reinforced handles, sized for daily carry.', price: 899, category: 'Bags', image: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&q=80', stock: 45, rating: 4.3, specifications: [{ label: 'Material', value: 'Heavy canvas' }] },
  { name: 'Everyday Backpack', description: 'A water-resistant backpack with a padded laptop sleeve and multiple organizer pockets.', price: 2799, category: 'Bags', image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&q=80', stock: 22, rating: 4.5, specifications: [{ label: 'Capacity', value: '20L' }, { label: 'Laptop sleeve', value: 'Up to 15"' }] },
  { name: 'Crossbody Sling Bag', description: 'A compact crossbody bag with an adjustable strap, made for essentials on the go.', price: 1299, category: 'Bags', image: 'https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&q=80', stock: 30, rating: 4.0, specifications: [{ label: 'Material', value: 'Nylon' }] },
  { name: 'Ceramic Coffee Mug Set', description: 'A set of two matte ceramic mugs, dishwasher and microwave safe.', price: 699, category: 'Lifestyle', image: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&q=80', stock: 3, rating: 4.4, specifications: [{ label: 'Set size', value: '2 mugs' }] },
  { name: 'Scented Soy Candle', description: 'A slow-burning soy wax candle with a warm sandalwood and amber scent, ~40hr burn time.', price: 599, category: 'Lifestyle', image: 'https://images.unsplash.com/photo-1602874801007-bd458bb1b8a6?w=800&q=80', stock: 4, rating: 4.6, specifications: [{ label: 'Burn time', value: '~40 hours' }] },
];
